### ISSUE TITLE
WordPress.org screenshot

### ISSUE THREAD

**Issue by slaFFik** [spatie/wordpress-ray#13]
Your screenshot should be uploaded to the svn repo (they do not allow to embed them on wordpress.org).

Upload it to `assets/screenshot-1.png` file.
Together with my PR that changes some things - the screenshot will appear on the plugin page here: https://wordpress.org/plugins/spatie-ray/

**Comment by freekmurze** [comment]
Is this what you meant? https://github.com/spatie/wordpress-ray/commit/f6c241e7831a3bb97166bf4657aa79f628820390

**Comment by slaFFik** [comment]
No, you don't need to link to the file. If the file with the name `screenshot-1.png` is present in `assets` dir in SVN repo - it will be automatically picked up by wordpress.org and display in the Screenshots area of the plugin description. It matches the `1. Some screenshot description` to `screenshot-1.png`, `2. Some other screenshot` to `screenshot-2.png` etc.

Related doc: https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/

**Comment by slaFFik** [comment]
@freekmurze I've added a lot more details ^ after my initial comment, so pinging you so that you won't miss it.

**Comment by freekmurze** [comment]
@slaFFik it's a tad confusing to me, could you create a PR with the needed changes?

**Comment by slaFFik** [comment]
I can't because the screenshots should be NOT in the git repo here, but in the SVN repo which I don't have access to.

**Comment by freekmurze** [comment]
But the files in this git repo will be pushed to the SVN repo right? So I'm thinking I should put them here in order to have them in SVN.

**Comment by slaFFik** [comment]
In that case, you will need to manually relocate them before each release.
So, from `assets/wporg/*` inside this git repo to `SVNRepo/assets`.

**Comment by freekmurze** [comment]
So, I need to do that with a SVN client, directly on SVN?

**Comment by freekmurze** [comment]
On it 🙂 
<img width="501" alt="image" src="https://user-images.githubusercontent.com/483853/104452432-49bbb280-55a3-11eb-8751-2ed9111142e2.png">

**Comment by slaFFik** [comment]
Yes, correct.

Here is an example of the SVN repo of one of the plugins (`wp-mail-smtp`):
![image](https://user-images.githubusercontent.com/282234/104452225-5b08bd00-55ab-11eb-9d72-d84d06f20bee.png)

Check the path:
`WordPressSVN` is a directory with all of my WP.org plugins.
`wp-mail-smtp` is a directory where I ran `svn co` for one specific plugin (in your case that will be `spatie-ray`).
This plugin SVN repo has these directories:
```
assets/
branches/
tags/
trunk/
```
So that `WordPressSVN\wp-mail-smtp\assets` is a SVN dir that I'm talking about.

**Comment by slaFFik** [comment]
Also, you version in the `readme.txt` should be equal to the tag in `tags/`.
So as you released `1.0.0` already (according to readme.txt), you next tag should be above that version. Also you need.

I'm saying that because I see 0.0.8 in the SVN repo on your screenshot.

BTW, updates to the plugin are live in several minutes at most, no review process. That's only the initial version that should be reviewed by a human.

**Comment by freekmurze** [comment]
@slaFFik do you know how to get rid of this message at https://wordpress.org/plugins/spatie-ray/?

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/483853/104453435-b1bec880-55a4-11eb-8edb-4a2a015cd8fc.png">

**Comment by slaFFik** [comment]
I believe you should update the readme.txt file inside the `trunk/` as well. I don't remember that by heart, but I usually have a copy of the plugin inside the latest `/tags/X.X.X` and `trunk` - both places with the same code.

Re:notice - yes, your current `readme.txt` in this repo will remove that notice :)

**Comment by jeffreyvr** [comment]
@freekmurze You can also use a Github action to automatically publish releases from Github to SVN.

Here is an example of a plugin of mine: https://github.com/jeffreyvr/easy-liveblogs/blob/master/.github/workflows/release.yml

You can then also store your [assets](https://github.com/jeffreyvr/easy-liveblogs/tree/master/.wordpress-org), like screenshots, on your repo. This way you don't have to use SVN anymore.

**Comment by slaFFik** [comment]
@freekmurze There was a typo in the readme.txt, I fixed that in https://github.com/spatie/wordpress-ray/pull/16 so that will definitely remove the notice.

**Comment by freekmurze** [comment]
Thanks!

**Comment by freekmurze** [comment]
We will add a screenshot later today! Thanks for all the help 👍
