### ISSUE TITLE
GitHub release asset not containing a "spatie-ray" directory

### ISSUE THREAD

**Issue by szepeviktor** [spatie/wordpress-ray#17]
- WordPress plugin ZIP-s should have a main directory with all file inside it, https://downloads.wordpress.org/plugin/spatie-ray.zip
- Please do not distribute developments stuff: `.git/` etc.

**Comment by szepeviktor** [comment]
Please see https://github.com/10up/action-wordpress-plugin-deploy#excluding-files-from-deployment

**Comment by freekmurze** [comment]
It's not clear to me how to enable this. Could you send a PR that fixes this?

**Comment by szepeviktor** [comment]
10up's action may be buggy

![kép](https://user-images.githubusercontent.com/952007/104483469-6f0ee780-55c8-11eb-92be-66a49f5b2596.png)

**Comment by szepeviktor** [comment]
I seeeeeeeeeeeeeeeeeeee :)
https://github.com/spatie/wordpress-ray/blob/master/.distignore

**Comment by szepeviktor** [comment]
Actually wrapping everything in a "spatie-ray" directory will not happen (yet)

**Comment by szepeviktor** [comment]
WordPress core manages to extract our main-directory-less GitHub release ZIP to a directory with the name of the ZIP file...

**Comment by szepeviktor** [comment]
BTW `/vendor` could be removed from the repo and added to the release ZIP only. And namespaces be mozart-ed...

**Comment by freekmurze** [comment]
I don't know what "Mozart-ed" means. Feel free to PR improvements.

**Comment by szepeviktor** [comment]
https://github.com/coenjacobs/mozart wraps all dependencies in a Spatie namespace so if other WP plugins include another (major) version of that dependency we won't have conflicts.

**Comment by Mamaduka** [comment]
@szepeviktor that's already done by `imposter-plugin` [package](https://github.com/TypistTech/imposter-plugin).

**Comment by szepeviktor** [comment]
Really :)

https://github.com/spatie/wordpress-ray/blob/144df103a5d1ca090adfc2a088a5a4d3aeb5f458/composer.json#L27
