### ISSUE TITLE
Wordpress Plugin version 1.0.2 not working as expected

### ISSUE THREAD

**Issue by ajimatahari** [spatie/wordpress-ray#22]
the github version (1.0.0) works fine. but then the plugin release on wordpress plugin repo (v1.0.2), I try to update it to 1.0.2, then the plugin not working. does not show anything on ray app.

Then i try to downgrade it again to version 1.0.0, it works again. so i think the bugs is exist on version 1.0.2

**Comment by w3guy** [comment]
I just came here to complain too.

https://github.com/spatie/laravel-ray/issues/92

**Comment by jeffreyvr** [comment]
Make sure your `WP_ENVIRONMENT_TYPE` constant is set in your `wp-config.php` file. If you don't, it will assume you are on a production environment - in which case Ray won't be enabled.

For local development specify:

```php
define( 'WP_ENVIRONMENT_TYPE', 'local' );
```

**Comment by ihorvorotnov** [comment]
> Make sure your `WP_ENVIRONMENT_TYPE` constant is set in your `wp-config.php` file. If you don't, it will assume you are on a production environment - in which case Ray won't be enabled.

This should be mentioned in the docs. `WP_ENVIRONMENT_TYPE` is quite new and not everyone uses it yet.

**Comment by freekmurze** [comment]
I'll be improving the environment check in 1.0.3 which will be released shortly: https://github.com/spatie/wordpress-ray/commit/9f84822115a6fae9867512f1db6a70688df1cc66

**Comment by freekmurze** [comment]
I think it's already mentioned in the docs. Feel free to send a PR to make things more clear (there's an edit button on every page)

**Comment by ihorvorotnov** [comment]
Yes, now it is (wasn't there the last time I checked). Things are changing fast! 😉
