### ISSUE TITLE
Autocomplete does not work in phpStorm with the plugin. Works with composer.

### ISSUE THREAD

**Issue by deryckoe** [spatie/wordpress-ray#23]
If I use the plugin, autocomplete does not work.

![1-with-plugin-no-composer](https://user-images.githubusercontent.com/2091762/104623881-97065580-5671-11eb-9a99-1acd941975c6.jpg)

If I remove the plugin and use composer, works.

<img width="1036" alt="2-with-composer-no-plugin" src="https://user-images.githubusercontent.com/2091762/104623905-a1285400-5671-11eb-88b6-5d66754b84a2.png">

**Comment by deryckoe** [comment]
After running `composer install` inside the plugin folder, autocomplete started working in phpStorm.

**Comment by freekmurze** [comment]
This has been fixed in `1.1.0`
