### ISSUE TITLE
Fatal error on DateCaster::castDateTime

### ISSUE THREAD

**Issue by lmartins** [spatie/wordpress-ray#26]
After installing the latest version of the WP plugin, started getting this fatal error:

```
Fatal error: Uncaught TypeError: Argument 3 passed to Symfony\Component\VarDumper\Caster\DateCaster::castDateTime() must be an instance of Symfony\Component\VarDumper\Cloner\Stub, instance of Spatie\WordPressRay\Symfony\Component\VarDumper\Cloner\Stub given, called in /Users/luismartins/Sites/project/wp-content/plugins/spatie-ray/vendor/symfony/var-dumper/Cloner/AbstractCloner.php on line 303 and defined in /Users/luismartins/Sites/project/wp-content/themes/project/vendor/symfony/var-dumper/Caster/DateCaster.php on line 27
```

**Comment by freekmurze** [comment]
@jeffreyvr do you know a good way of fixing this one?

**Comment by jeffreyvr** [comment]
Just to be sure @lmartins, are you running version 1.1.1? I would think that this issue was fixed within the latest release.

Could you otherwise provide a code snippet so that I can replicate the situation?

**Comment by lmartins** [comment]
@jeffreyvr I did updated both the app and the WordPress plugin, but I am now unable to replicate the issue. This was happening in the admin (working on gutenberg blocks). 

Since I can't replicate anymore, I'm going to close this one if that's okay. If I do see it again I'll report back.

Thanks so much for jumping on this.
