### ISSUE TITLE
Doesn't work on Docker, Windows 10

### ISSUE THREAD

**Issue by jonochong** [spatie/wordpress-ray#27]
I'm running WordPress on Docker Desktop (Version 3.0.4)
Plugin installed (Version 1.1.1)
Added "define( 'WP_ENVIRONMENT_TYPE', 'local' );" in wp-config.php
In plugin, ray("hello"); and also error_log("Hello");
"Hello" in debug.log
Nothing in Ray.

Tried adding in docker-compose:
extra_hosts:
      - "host.docker.internal:host-gateway"
   
Still nothing.

Docker compose file for reference:

version: '3'
services:
    database:
        image: mysql:5.7
        command:
            - "--character-set-server=utf8"
            - "--collation-server=utf8_unicode_ci"
        ports:
            - "3308:3306" # (*)
        restart: on-failure:5
        environment: 
            MYSQL_USER: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_PASSWORD: wordpress
            MYSQL_ROOT_PASSWORD: wordpress
    wordpress:
        depends_on:
            - database
        image: wordpress:latest
        ports:
            - "8001:80" # (*)
        restart: on-failure:5
        volumes:
            - ./public:/var/www/html
        environment:
            WORDPRESS_DB_HOST: database:3306
            WORDPRESS_DB_PASSWORD: wordpress
        extra_hosts:
            - "host.docker.internal:host-gateway"
    phpmyadmin:
        depends_on:
            - database
        image: phpmyadmin/phpmyadmin
        ports:
            - 8081:80 # (*)
        restart: on-failure:5
        environment:
            PMA_HOST: database

Any ideas?

Thank you!

**Comment by freekmurze** [comment]
Could you try mapping port 23517
- "23517:23517"

**Comment by jonochong** [comment]
Thank you for the suggestion. 

I tried mapping "23517:23517" for wordpress. No joy. 
netstat returns

TCP    0.0.0.0:23517          0.0.0.0:0              LISTENING       22216
TCP    [::]:23517             [::]:0                 LISTENING       22216

I tried changing the port on Ray to 22216, but still nothing.

**Comment by freekmurze** [comment]
Then, I don't know...

The desktop app just listens for messages on the port. The Ray package just sends things to that port.

I guess you should research how you can open a port on Docker on how to map that to a port on your native environment.

**Comment by jonochong** [comment]
Understood. Thank you for pointing me in the direction! Cheers!

**Comment by deibertf** [comment]
I can confirm this is an issue. I've included the port to my docker-compose.yml but no `ray()` calls show up in my app.
I am calling ray from a wordpress plugin :/
