### ISSUE TITLE
Missing new label() method

### ISSUE THREAD

**Issue by templeman** [spatie/wordpress-ray#43]
WordPress Ray throws an error when attempting to use the ([newly introduced](https://github.com/spatie/ray/blob/main/CHANGELOG.md#1290---2021-08-02)) `label` method.

```
Uncaught BadMethodCallException: Method label does not exist. in /web/app/mu-plugins/spatie-ray/vendor/spatie/macroable/src/Macroable.php:53
```

**Comment by freekmurze** [comment]
This function is available in the newly released v.1.4 of spatie/wordpress-ray

**Comment by templeman** [comment]
👍  Thank you!
