### ISSUE TITLE
PHP 8.1 deprecation notice 

### ISSUE THREAD

**Issue by UVLabs** [spatie/wordpress-ray#53]
Identical to this: https://github.com/spatie/wordpress-ray/issues/49

But it doesn't seem like a release was made? I tried pulling down latest master branch and its already up to date on my system

**Comment by freekmurze** [comment]
I've just created a new release that should fix this.

**Comment by squaredpx** [comment]
Should v1.5.4 fix this issue? I'm using it but I'm still getting the same PHP notice while using PHP 8.1. I don't know if it's the same issue or a different one but I'm getting the same notice
