### ISSUE TITLE
PHP 8.1 deprecation notice on v1.5.4

### ISSUE THREAD

**Issue by squaredpx** [spatie/wordpress-ray#54]
I'm seeing a PHP deprecation notice on the latest plugin version after updating PHP to 8.1.

- PHP: 8.1
- WordPress: 6.1.1
- WordPress Ray Plugin: 1.5.4

When the plugin is active this deprecation notice show up on every page load:

`Deprecated: Return type of Spatie\WordPressRay\Ramsey\Uuid\Uuid::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ..plugins/spatie-ray/vendor/ramsey/uuid/src/Uuid.php on line 159`

An these ones only when there is a call to the ray() function:

`Deprecated: Return type of Spatie\WordPressRay\Symfony\Component\VarDumper\Cloner\Data::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ..plugins/spatie-ray/vendor/symfony/var-dumper/Cloner/Data.php on line 133`

`Deprecated: Return type of Spatie\WordPressRay\Symfony\Component\VarDumper\Cloner\Data::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ..plugins/spatie-ray/vendor/symfony/var-dumper/Cloner/Data.php on line 137`

`Deprecated: Return type of Spatie\WordPressRay\Symfony\Component\VarDumper\Cloner\Data::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ..plugins/spatie-ray/vendor/symfony/var-dumper/Cloner/Data.php on line 141`

`Deprecated: Return type of Spatie\WordPressRay\Symfony\Component\VarDumper\Cloner\Data::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ..plugins/spatie-ray/vendor/symfony/var-dumper/Cloner/Data.php on line 101`

`Deprecated: Return type of Spatie\WordPressRay\Symfony\Component\VarDumper\Cloner\Data::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ..plugins/spatie-ray/vendor/symfony/var-dumper/Cloner/Data.php on line 108`

**Comment by freekmurze** [comment]
I'm not sure what we can do about this as the notice is triggered in the vendor files generated by scopes.

@jeffreyvr do you have an idea how to avoid these notices?

**Comment by jeffreyvr** [comment]
@freekmurze I think if you add 8.1 to `composer.json` and then run the build script, those notices might disappear. PHP Scope seems to support 8.1. Haven't had the time to test it yet.

**Comment by freekmurze** [comment]
I've bumped the dependencies, ran the build script and tagged a new release. Hopefully that will fix this problem.

**Comment by TorbenLundsgaard** [comment]
The problem has not been fixed. I thing that you need to require `"ramsey/uuid": "3.9.6"`

**Comment by freekmurze** [comment]
Just a tagged a new release 1.5.6

Let me know if that works for you.

**Comment by squaredpx** [comment]
Yes, the notices are gone. Thanks!
