### ISSUE TITLE
PHP Version Requirements

### ISSUE THREAD

**Issue by craigsimps** [spatie/wordpress-ray#55]
In the plugin file, the requirement is for a minimum PHP version of 7.3. 

https://github.com/spatie/wordpress-ray/blob/master/wp-ray.php#L11

Changes overnight, in 2c5bb668382d98ee0818ff027d500cf6de079342 have introduced a minimum PHP version of 8.0 https://github.com/spatie/wordpress-ray/blob/master/vendor/composer/platform_check.php#L7

This had the unfortunate side effect of crashing one of my websites when it was pushed to the WordPress.org plugin repository and the plugin auto-updated overnight.

I realise work is ongoing to add support for PHP8.1, and I'm not at all against the minimum PHP version being raised to 8.0. But parity between these two versions (the plugin minimum, and the minimum for Composer) should be maintained.

**Comment by JiveDig** [comment]
I'd like to add a vote to support PHP 7 for a bit longer. We have some sites that we can't update to PHP 8 yet due to legacy code that we haven't updated. I'd love to continue to use Ray on these sites, but as of now I can't.

**Comment by lopadz** [comment]
Same here. Need to be able to use with outdated PHP versions due to legacy codebases.

**Comment by freekmurze** [comment]
For support for older PHP version, you can use v1.5.2 of the plugin.

**Comment by craigsimps** [comment]
Agreed - for supporting older versions of PHP the older version of the plugin is available. 

However, the plugin file still says that it supports PHP version 7.3 and up. If a website owner has automatic updates enabled, then they will be automatically updated to the newest version. If they are running PHP <8.0, they will get a fatal error, as in my original comment because of the code in https://github.com/spatie/wordpress-ray/commit/2c5bb668382d98ee0818ff027d500cf6de079342

The Requires header at https://github.com/spatie/wordpress-ray/blob/master/wp-ray.php#L11 should be updated to 8.0 to match the plugin's requirements, and prevent sites being automatically updated if they are unable to support the plugin.

**Comment by freekmurze** [comment]
@craigsimps I've released a new version where the plugin requirements are updated.
