### ISSUE TITLE
Fatal error when installing on PHP 7.4

### ISSUE THREAD

**Issue by aaemnnosttv** [spatie/wordpress-ray#56]
The current stable version 1.5.6 raises a fatal error when activating the plugin. This can be observed using a clean install of WP using PHP 7.4 which the plugin declares support for.

```
Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.0". You are running 7.4.30. in /s2-hissingfinger/wordpress/wp-content/plugins/spatie-ray/vendor/composer/platform_check.php on line 24
```

You can see this in action here: https://tastewp.org/plugins/spatie-ray/

![image](https://user-images.githubusercontent.com/1621608/209891072-a21ad28b-a5d5-4767-8a72-60c3b74d468e.png)

---

As an aside, I would suggest not raising the minimum required version of PHP to 8.0 as many sites still run on 7.4 – the majority of WP sites actually! See https://wordpress.org/about/stats/
Whether or not they should is another question 😄 Of course PHP 7 is EOL now, but dropping support for it this quickly is rather aggressive for a dev tool IMHO.

Whenever the required version of PHP is changed though, it's important to update this in the `readme.txt` for the PHP version constraints to work as expected.

**Comment by freekmurze** [comment]
I've fixed this in the readme.txt in v1.6.0 after I forgot it in v1.5.6

I wonder if there is a way to unpublished v1.5.6, so people on PHP 7 would get v1.5.5

**Comment by jeffreyvr** [comment]
I think you could alter the minimum PHP version:
https://developer.wordpress.org/plugins/wordpress-org/how-to-use-subversion/#editing-existing-files

Or maybe delete the version entirely, although the instructions on that in the documentation are less then helpful:
https://developer.wordpress.org/plugins/wordpress-org/how-to-use-subversion/#delete-old-versions

**Comment by aaemnnosttv** [comment]
> I wonder if there is a way to unpublished v1.5.6, so people on PHP 7 would get v1.5.5

As @jeffreyvr mentioned, I believe you could update the `readme.txt` for the 1.5.6 tag in subversion.
