### ISSUE TITLE
Fatal error: Return value

### ISSUE THREAD

**Issue by carstenjaksch** [spatie/wordpress-ray#67]
I have a weird error. Just installed Ray to debug an issue. But didn't expect that the debugger needs debugging. 😁 

```php
ray('test'); // After that, this error comes in WP All Export:
// Fatal error: Uncaught Error: Spatie\WordPressRay\Spatie\Ray\Payloads\Payload::getOrigin(): Return value must be of type Spatie\WordPressRay\Spatie\Ray\Origin\Origin, Spatie\Ray\Origin\Origin returned
```

Installed is WordPress 6.1.1 and PHP 8.0 – tested with PHP 8.1 too.

I tried to debug the code inside an action called `pmxe_after_export` within the functions.php – which I was debugging multiple times in the past and deinstalled Ray afterwards.

**Comment by jeffreyvr** [comment]
How did you install Ray and what version are using? I've tried to reproduce the error with WP All Export and the hook you are using, but I'm not getting this error.

**Comment by carstenjaksch** [comment]
I installed Ray the default way – with the WordPress plugin directory. It is the newest version.

**Comment by jeffreyvr** [comment]
That's what I did too. To be sure, I'm using v1.7.4 and use PHP 8.1. Can you provide the full stack trace of the error?

**Comment by carstenjaksch** [comment]
Well I installed it with PHP 8.0 active. Maybe that is the issue? A stack trace was not displayed.

**Comment by jeffreyvr** [comment]
I've tested both PHP 8.0 (including re-install of the plugin) and 8.1 but I don't have the error occurring. Perhaps you can turn on the [debug log](https://wordpress.org/documentation/article/debugging-in-wordpress/#wp_debug_log). That should provide a stack trace..
